### ISSUE TITLE
NEW API Error

### ISSUE THREAD

**Issue by ac3dev** [nfarina/homebridge-liftmaster#10]
I keep getting this error:

Loaded plugin: homebridge-liftmaster
Registering accessory 'homebridge-liftmaster.LiftMaster'
---
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded config.json with 1 accessories and 1 platforms.
---
Loading 1 platforms...
Initializing Nest platform...
Fetching Nest devices.
Loading 1 accessories...
[Home] Initializing LiftMaster accessory...
[Error: You did not specify {'token'} or {'clientId','clientSecret','code'}, one set of which is required for the new API]
Falling back to legacy API.

Any idea how to fix it?

**Comment by AppleTechy** [comment]
@nfarina Please close this issue..... Issue with Nest not Liftmaster API
