### ISSUE TITLE
Any way to control 2 doors on the same account, independently? 

### ISSUE THREAD

**Issue by TheHavocHero** [nfarina/homebridge-liftmaster#14]
I have 2 doors on my Chamberlain account. Is there anyway to control them independently with homekit? I have them setup as 2 individual accessories, but Siri opens and closes them both at the same time. They have different names. My settings look like this..

```
"accessories": [
        {
      "accessory": "LiftMaster",
      "name": "Garage Door",
      "username": "<<username>>",
      "password": "<<password>>",
      "deviceID": "11111111"
    },
        {
      "accessory": "LiftMaster",
      "name": "Second Garage Door",
      "username": "<<username>>",
      "password": "<<password>>",
      "deviceID": "2222222"
```

**Comment by danoday** [comment]
Sure.  There are actually two names assigned to each door.  One is the name you see in the JSON file, and the other is the "Siri" name.  Siri is probably defaulting both of them to "Garage Door".

Use a HomeKit app to drill into the information for the accessory, and find that "Siri" name (the field title seems to vary with different apps, so just dig around).  Make them distinct for each door, and you should be good to go.

**Comment by TheHavocHero** [comment]
Thanks for the reply. I am using MyTouchHome and I can see my devices and names there, but renaming them in the app seems to have no effect. What app do you use?

**Comment by danoday** [comment]
I use both Insteon+ and Elgato Eve for free apps, but prefer the paid "Home" app.  A bit cleaner.  Insteon+ seems to limit having a Siri name and an accessory name match, but the others don't seem to mind this.  Have you bounced the Homebridge process so it reloads?  Not sure if this is necessary, but seems like a good step to test.  If that doesn't work, let's set up a time to chat via the Homebridge Slack channel, and I'll talk you through changing the Siri name with whatever app you have.

I would suggest giving each door a unique name that is not "Garage Door".  I use "Big Garage Door" and "Small Garage Door" myself, which seems to work well.

**Comment by TheHavocHero** [comment]
Thanks. I needed up purchasing Home and that does work better. I assume the Siri name is the Service Name in the app? That did seem to work, but I find that when I tell it to close on of the door names, it reverts to closing all garage doors. 

What does Identify do under more information? Also, I have bounced the Homebridge process a few times now, whenever I change a name in my ISY.

**Comment by AppleTechy** [comment]
@TheHavocHero Have you figured everything out?

**Comment by TheHavocHero** [comment]
Yes. I was able to rename the SIRI name in the Home app for each garage door and called one "first garage door" and the other "second garage door". This solved most of my issues. I still find every once in a while that Siri opens or closes both doors when I specify one or the other.

**Comment by AppleTechy** [comment]
Alright glad to hear you got it working!
