### ISSUE TITLE
Allow Craftsman AssureLink control.

### ISSUE THREAD

**Issue by derekmoyes** [nfarina/homebridge-liftmaster#15]
Howdy,

I have this plugin controlling my Craftsman AssureLink, but I had to make a couple of changes to the index.js file.

/usr/local/lib/node_modules/homebridge-liftmaster/index.js

The line that shows:
var APP_ID = "JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu"
Change to:
var APP_ID = "eU97d99kMG4t3STJZO/Mu2wt69yTQwM0WXZA5oZ74/ascQ2xQrLD/yjeVhEQccBZ"

Then, find three lines that are similar to this:
url: "https://myqexternal.myqdevice.com/ ...
and change them all to:
url: "https://craftexternal.myqdevice.com/...

I'm guessing you could enable a config option called craftsman = true to make this happen, but I'm not sure how to do it.

Anyways, thanks for the great app, and these nifty plugins!

**Comment by AppleTechy** [comment]
I believe there is a AssureLink MYQ plugin already created if u wanted to
give that a spin and see if there are anymore indepth changes. Good Luck!

**Comment by derekmoyes** [comment]
Interesting that I didn't find that when I was searching for my garage door. >_< 

Also, that plugin looks like a fork of this one, with the requisite changes made.
