### ISSUE TITLE
Liftmaster Gate

### ISSUE THREAD

**Issue by satish-dharmaraj** [nfarina/homebridge-liftmaster#19]
I have 2 gates and 2 garage doors. The garage doors work beautifully. Thanks! But I get an error while adding the gates as accessories although the deviceID is correct for each gate

Error: Couldn't find a door device, or the ID you specified isn't associated with your account

**Comment by satish-dharmaraj** [comment]
Ok fixed it by changing index.js to also check for type "Gate" in addition to "Garage Door". Worked like a charm. Thanks. LMK if you want me to contribute it back - its an easy one line fix.

**Comment by AppleTechy** [comment]
Go ahead and create a pull request for it. As long as it doesn't break anything in the plugin, I would be more than happy to add it
