### ISSUE TITLE
Status never shows open

### ISSUE THREAD

**Issue by thewings** [nfarina/homebridge-liftmaster#2]
I can control the garage door perfectly, but if you query the state, it will always show closed - even if the door is open.

**Comment by jw59** [comment]
I second this problem.  I'm using a Chamberlain with MyQ embedded and the fix for those devices in this Pull Request.  

https://github.com/nfarina/homebridge-liftmaster/pull/1

**Comment by JerGitHub** [comment]
@donoday and I have similar issues but all 3 of mine show open when they are closed and vice versa. See issue https://github.com/nfarina/homebridge-liftmaster/issues/6 for more info.

**Comment by AppleTechy** [comment]
@jw59 and @thewings are you still having issues even after the latest update?

**Comment by jw59** [comment]
I installed the update manually a while back. It made my Chamberlain device work however the door state always remains closed.  Haven't spent much time looking into it since.

**Comment by AppleTechy** [comment]
@jw59 What app are you using?

**Comment by AppleTechy** [comment]
issue #25

**Comment by jw59** [comment]
Home and MyTouchHome.  Mostly though just Siri for control.  

I just realized there was another pull request around this issue that I haven't installed yet.  Disregard my comment about it not working.  The only fix I installed manually was for the Chamberlain branded devices.

**Comment by AppleTechy** [comment]
@jw59 Just update to the newest version and it should have fixed the issue with not refreshing the state when using multiple garage doors

**Comment by thewings** [comment]
Sorry for the late reply, but with all of the latest updates, my garage door is still always showing as closed - even if it is open. I am able to ask siri to open or close the door and it does work - it just does not show the correct status.
