### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by iRayanKhan** [nfarina/homebridge-liftmaster#25]

**Comment by AppleTechy** [comment]
You need to use add in the basic home bridge config that defines a Mac address and pin. Look at the example config on the home bridge repo, and combine it with what u currently have

**Comment by iRayanKhan** [comment]
I'll try it

**Comment by iRayanKhan** [comment]
Kinda fixed the issue it was working then this happened:
<img width="788" alt="screen shot 2018-03-06 at 6 39 49 pm" src="https://user-images.githubusercontent.com/34495712/37067082-d7624850-216d-11e8-906c-c743ecfc85d6.png">

**Comment by iRayanKhan** [comment]
For future reference I just had to delete the persist folder
