### ISSUE TITLE
Multiple Liftmaster Doors

### ISSUE THREAD

**Issue by JerGitHub** [nfarina/homebridge-liftmaster#4]
I am having issues with the 3 Doors I have. I did specify the 3  Doors with the Device ID in the config.js file. And it doesn't kick an error on running homebridge. When I go to try to do anything with my Doors - homebridge quits and throws the errors below. Any ideas on what to try? Thanks!

[My Garage Door] Logged in with user ID 0
[My Garage Door] WARNING: You have multiple doors on your MyQ account.
[My Garage Door] WARNING: Specify the ID of the door you want to control using the 'requiredDeviceId' property in your config.json file.
[My Garage Door] WARNING: You can have multiple liftmaster accessories to cover your multiple doors
[My Garage Door] Found Door: ####### - 1 Garage Door
[My Garage Door] Found Door: ####### - 2 Garage Door
[My Garage Door] Found Door: ####### - 3 Garage Door

/opt/local/lib/node_modules/homebridge-liftmaster/index.js:147
          throw "FATAL: Please specify which specific door this Liftmaster accessory should control - you have multiples on your account";
          ^
FATAL: Please specify which specific door this Liftmaster accessory should control - you have multiples on your account

**Comment by AppleTechy** [comment]
Sorry I wish I could help you but I can't even login into my account via homebridge I am returned with a server error :( My guess is you formatting is correct but that you are missing a comma or brackets or something. Could you post your config for the devices without your personal information included, this way we can doubt check that your formatting is correct for the plugin to read not just JSON. Good Luck, Apple T.

**Comment by JerGitHub** [comment]
Thanks for helping. Here's my config.json with user/pass and Device ID's changed but everything else in place. Nest is working fine.

rhapsody:.homebridge jer$ cat config.json
{

    "bridge": {
        "name": "rhapsody-homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },

  "accessories": [
    {
      "accessory": "LiftMaster",
      "name": "Aux Garage Door",
      "username": “me@me.com”,
      "password": “password”,
      "deviceID": “1234567”
    }
  ],
  "accessories": [
    {
      "accessory": "LiftMaster",
      "name": "L Garage Door",
      "username": “me@me.com”,
      "password": “password”,
      "deviceID": “1234568”
    }
  ],
  "accessories": [
    {
      "accessory": "LiftMaster",
      "name": “J Garage Door",
      "username": “me@me.com”,
      "password": “password”,
      "deviceID": “1234569”
    }
  ],

"platforms": [
    {
      "platform": "Nest",
      "name": "Nest",
      "username" : “me@me.com”,
      "password" : “password”
    }					       
 ]
}

**Comment by danoday** [comment]
I had a similar issue.  Digging through the code, it looked like "deviceID" might not have been the proper string to use.  Instead, "requiredDeviceID" seemed to invoke the correct logic (in the IF statement).  I added "requiredDeviceID" to config.json and got it to work with multiple doors.

this.requiredDeviceId = config["requiredDeviceId"];
...
if (!that.requiredDeviceId) ...

	"accessories": [{
		"accessory": "LiftMaster",
		"name": "Big Garage Door",
		"username": "e-mail@domain.com",
		"password": "passw0rd",
		"deviceID": "1234567",
		"requiredDeviceId": "1234567"
	},
{
		"accessory": "LiftMaster",
		"name": "Small Garage Door",
		"username": "email@domain.com",
		"password": "passw0rd",
		"deviceID": "1234568",
		"requiredDeviceId": "1234568"
	}]
}

Worth noting that the status doesn't seem to report directly.  My doors report the status as "open" all the time, although Siri will allow me to open and close them without problems.  Still can't identify the part of the code that gets "doorstatus" when you have multiple doors, but am a relative Java newbie.

Also, when you have multiple doors, make sure to give them unique Siri names (not just the device names).  For me, both doors defaulted to "Garage Door", so Siri got confused.

**Comment by AppleTechy** [comment]
@JerGitHub Sorry for the delayed response. Where you able to get it to successfully run?

**Comment by JerGitHub** [comment]
Thanks for the help guys. I am not erroring out once I added "requiredDeviceId" and then try to look at the status in the Elgato Eve app but I also am not seeing all 3 of my doors - just the last one listed. I'm going to try and delete all my HomeKit data and start over with homebridge from scratch and delete the persist dir too. 

I assume @danoday you mean that I have to define the Siri names in an app like Elgato Eve like I did with my Nests?

Here's the current output from homebridge:

[My Garage Door] Logged in with user ID 0
[My Garage Door] Found an opener with ID 1234567 [doorstate: undefined]
[My Garage Door] Getting current state: undefined
[My Garage Door] Logged in with user ID 0
[My Garage Door] Found an opener with ID 1234567 [doorstate: undefined]
[My Garage Door] Getting current state: undefined

**Comment by danoday** [comment]
@JerGitHub - Glad the "requiredDeviceID" worked.  I think this is probably either a bug or a discrepancy in the documentation.  Nick's call on which way he wants to resolve this, though.

I named my garage doors "Big Garage Door" and "Small Garage Door", but these are apparently (using the terminology from the Elgato app) the "Accessory Name"s.  You can see these when you edit the accessory within the Elgato app.  From that same page, if you click "Features", you'll see a second box.  This is the name Siri knows the accessory as.  In my case, both my garage doors defaulted to a Siri name of "Garage Door", despite having different accessory names.  When I asked Siri "Is the Big Garage Door closed?", she got confused and said the garage doors were closed.  Defining unique Siri names for each fixed this.  For the problem with only seeing the last door in the app, I would suggest triple-checking the Siri names... it could be related to this.

Finally, I would try asking Siri for a specific garage door status and see how she responds.  You might also have issues with reporting proper status - check out issue #6 for more on that.  If you do get incorrect status, comment on that issue - I'd like to know it isn't just me!

**Comment by JerGitHub** [comment]
@danoday Sorry - Christmas had me busy. 

So yes - I got all 3 doors working with all of my Nests as well. Now I have the same issue as you (https://github.com/nfarina/homebridge-liftmaster/issues/6). All of my doors show "Open" with "Obstruction Detected - NO" when they are all closed. 

So....still can't use the LiftMaster plugin for HomeBridge yet. So close though! At least this issue is fixed. Thanks for your help.
